apiVersion: v2
name: atomi-otel-operator
description: Helm chart to deploy operator for OTEL collectors

type: application

version: 1.0.0

appVersion: "0.34.1"

dependencies:
  - name: opentelemetry-operator
    alias: otel
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.34.1
