# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service lithium
  module: &module operator
  layer: &layer "1"

# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  atomi.cloud/platform: *platform
  atomi.cloud/service: *service
  atomi.cloud/module: *module
  atomi.cloud/layer: *layer

# -- OTEL Collector Operator Configurations. See [OTEL Collector Operator Helm Chart Documentation](https://github.com/open-telemetry/opentelemetry-operator)
otel:
  replicaCount: 3
  manager:
    collectorImage:
      tag: v0.86.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
