serviceTree:
  landscape: &landscape pichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

otel:
  replicaCount: 1
  manager:
    resources:
      requests:
        cpu: 62m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
