version: "3"

env:
  RELEASE_NAME: sulfoxide-lithium

includes:
  util: tasks/Taskfile.util.yaml
  pichu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: opal
  pikachu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pikachu
      CLUSTER: opal
  raichu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: raichu
      CLUSTER: opal
  entei:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: entei
      CLUSTER: opal
tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get the latest version of OTEL Operator
    cmds:
      - task: util:latest
        vars:
          REPO_NAME: otel
          REPO_URL: https://open-telemetry.github.io/opentelemetry-helm-charts
          CHART_NAME: opentelemetry-operator
